import requests

def get_Country(server, token, movie_id, language):
    # 发送请求获取元数据
    headers = {'X-Plex-Token': token, 'Accept': 'application/json'}
    response = requests.get(f'{server}/library/metadata/{movie_id}', headers=headers)
    data = response.json()

    # 从响应中提取国家信息
    countries = data['MediaContainer']['Metadata'][0].get('Country', [])

    # 如果没有找到国家信息，返回 None
    if not countries:
        return None

    # 提取每个国家的名称
    country_names = [country['tag'] for country in countries]
    
    # 创建一个字典来存储国家名称的翻译
    country_translations = {
        'Afghanistan': ('Afghanistan', '阿富汗'),
        'Albania': ('Albania', '阿尔巴尼亚'),
        'Algeria': ('Algeria', '阿尔及利亚'),
        'American Samoa': ('American Samoa', '美属萨摩亚'),
        'Andorra': ('Andorra', '安道尔'),
        'Angola': ('Angola', '安哥拉'),
        'Anguilla': ('Anguilla', '安圭拉岛'),
        'Antarctica': ('Antarctica', '南极洲'),
        'Antigua and Barbuda': ('Antigua and Barbuda', '安提瓜和巴布达'),
        'Argentina': ('Argentina', '阿根廷'),
        'Armenia': ('Armenia', '亚美尼亚'),
        'Aruba': ('Aruba', '阿鲁巴岛'),
        'Australia': ('Australia', '澳大利亚'),
        'Austria': ('Austria', '奥地利'),
        'Azerbaijan': ('Azerbaijan', '阿塞拜疆'),
        'Bahamas': ('Bahamas', '巴哈马'),
        'Bahrain': ('Bahrain', '巴林'),
        'Bangladesh': ('Bangladesh', '孟加拉国'),
        'Barbados': ('Barbados', '巴巴多斯'),
        'Belarus': ('Belarus', '白俄罗斯'),
        'Belgium': ('Belgium', '比利时'),
        'Belize': ('Belize', '伯利兹'),
        'Benin': ('Benin', '贝宁'),
        'Bermuda': ('Bermuda', '百慕大'),
        'Bhutan': ('Bhutan', '不丹'),
        'Bolivia': ('Bolivia', '玻利维亚'),
        'Bosnia and Herzegovina': ('Bosnia and Herzegovina', '波斯尼亚和黑塞哥维那'),
        'Botswana': ('Botswana', '博茨瓦纳'),
        'Bouvet Island': ('Bouvet Island', '布韦岛'),
        'Brazil': ('Brazil', '巴西'),
        'British Indian Ocean Territory': ('British Indian Ocean Territory', '英属印度洋领地'),
        'British Virgin Islands': ('British Virgin Islands', '英属维尔京群岛'),
        'Brunei': ('Brunei', '文莱'),
        'Bulgaria': ('Bulgaria', '保加利亚'),
        'Burkina Faso': ('Burkina Faso', '布基纳法索'),
        'Burma': ('Burma', '缅甸'),
        'Burundi': ('Burundi', '布隆迪'),
        'Cambodia': ('Cambodia', '柬埔寨'),
        'Cameroon': ('Cameroon', '喀麦隆'),
        'Canada': ('Canada', '加拿大'),
        'Cape Verde': ('Cape Verde', '佛得角'),
        'Cayman Islands': ('Cayman Islands', '开曼群岛'),
        'Central African Republic': ('Central African Republic', '中非'),
        'Chad': ('Chad', '乍得'),
        'Chile': ('Chile', '智利'),
        'China': ('China', '中国'),
        'Christmas Island': ('Christmas Island', '圣诞岛'),
        'Clipperton Island': ('Clipperton Island', '克利珀顿岛'),
        'Cocos (Keeling) Islands': ('Cocos (Keeling) Islands', '科科斯（基林）群岛'),
        'Colombia': ('Colombia', '哥伦比亚'),
        'Comoros': ('Comoros', '科摩罗'),
        'Democratic Republic of the Congo': ('Democratic Republic of the Congo', '刚果民主共和国'),
        'Republic of the Congo': ('Republic of the Congo', '刚果共和国'),
        'Cook Islands': ('Cook Islands', '库克群岛'),
        'Coral Sea Islands': ('Coral Sea Islands', '珊瑚海群岛'),
        'Costa Rica': ('Costa Rica', '哥斯达黎加'),
        'Cote d\'Ivoire': ('Cote d\'Ivoire', '科特迪瓦'),
        'Croatia': ('Croatia', '克罗地亚'),
        'Cuba': ('Cuba', '古巴'),
        'Curaçao': ('Curaçao', '库拉索'),
        'Cyprus': ('Cyprus', '塞浦路斯'),
        'Czech Republic': ('Czech Republic', '捷克'),
        'Denmark': ('Denmark', '丹麦'),
        'Djibouti': ('Djibouti', '吉布地'),
        'Dominica': ('Dominica', '多米尼克'),
        'Dominican Republic': ('Dominican Republic', '多米尼加'),
        'Ecuador': ('Ecuador', '厄瓜多尔'),
        'Egypt': ('Egypt', '埃及'),
        'El Salvador': ('El Salvador', '萨尔瓦多'),
        'Equatorial Guinea': ('Equatorial Guinea', '赤道几内亚'),
        'Eritrea': ('Eritrea', '厄立特里亚'),
        'Estonia': ('Estonia', '爱沙尼亚'),
        'Ethiopia': ('Ethiopia', '埃塞俄比亚'),
        'Europa Island': ('Europa Island', '欧罗巴岛'),
        'Falkland Islands': ('Falkland Islands', '福克兰群岛'),
        'Faroe Islands': ('Faroe Islands', '法罗群岛'),
        'Fiji': ('Fiji', '斐济'),
        'Finland': ('Finland', '芬兰'),
        'France': ('France', '法国'),
        'French Guiana': ('French Guiana', '法属圭亚那'),
        'French Polynesia': ('French Polynesia', '法属波利尼西亚'),
        'French Southern Territories': ('French Southern Territories', '法属南部领地'),
        'Gabon': ('Gabon', '加蓬'),
        'Gambia': ('Gambia', '冈比亚'),
        'Georgia': ('Georgia', '乔治亚'),
        'Germany': ('Germany', '德国'),
        'Ghana': ('Ghana', '加纳'),
        'Gibraltar': ('Gibraltar', '直布罗陀'),
        'Glorioso Islands': ('Glorioso Islands', '格洛里厄斯群岛'),
        'Greece': ('Greece', '希腊'),
        'Greenland': ('Greenland', '格陵兰'),
        'Grenada': ('Grenada', '格林纳达'),
        'Guadeloupe': ('Guadeloupe', '瓜德罗普岛'),
        'Guam': ('Guam', '关岛'),
        'Guatemala': ('Guatemala', '危地马拉'),
        'Guernsey': ('Guernsey', '根西岛'),
        'Guinea': ('Guinea', '几内亚'),
        'Guinea-Bissau': ('Guinea-Bissau', '几内亚比绍'),
        'Guyana': ('Guyana', '圭亚那'),
        'Haiti': ('Haiti', '海地'),
        'Holy See (Vatican City)': ('Holy See (Vatican City)', '罗马教廷（梵蒂冈城）'),
        'Honduras': ('Honduras', '洪都拉斯'),
        'Hungary': ('Hungary', '匈牙利'),
        'Hong Kong': ('Hong Kong SAR China', '中国香港'),
        'Hong Kong SAR China': ('Hong Kong SAR China', '中国香港'),
        'Iceland': ('Iceland', '冰岛'),
        'India': ('India', '印度'),
        'Indonesia': ('Indonesia', '印度尼西亚'),
        'Iran': ('Iran', '伊朗'),
        'Islamic Republic of Iran': ('Iran', '伊朗'),
        'Iraq': ('Iraq', '伊拉克'),
        'Ireland': ('Ireland', '爱尔兰'),
        'Isle of Man': ('Isle of Man', '马恩岛'),
        'Israel': ('Israel', '以色列'),
        'Italy': ('Italy', '意大利'),
        'Jamaica': ('Jamaica', '牙买加'),
        'Jan Mayen': ('Jan Mayen', '扬马延岛'),
        'Japan': ('Japan', '日本'),
        'Jersey': ('Jersey', '泽西岛'),
        'Jordan': ('Jordan', '约旦'),
        'Juan de Nova Island': ('Juan de Nova Island', '新胡安岛'),
        'Kazakhstan': ('Kazakhstan', '哈萨克斯坦'),
        'Kenya': ('Kenya', '肯尼亚'),
        'Kiribati': ('Kiribati', '基里巴斯'),
        'Kosovo': ('Kosovo', '科索沃'),
        'Kuwait': ('Kuwait', '科威特'),
        'Kyrgyzstan': ('Kyrgyzstan', '吉尔吉斯斯坦'),
        'Laos': ('Laos', '老挝'),
        'Latvia': ('Latvia', '拉脱维亚'),
        'Lebanon': ('Lebanon', '黎巴嫩'),
        'Lesotho': ('Lesotho', '莱索托'),
        'Liberia': ('Liberia', '利比里亚'),
        'Libya': ('Libya', '利比亚'),
        'Liechtenstein': ('Liechtenstein', '列支敦士登'),
        'Lithuania': ('Lithuania', '立陶宛'),
        'Luxembourg': ('Luxembourg', '卢森堡'),
        'Macedonia': ('Macedonia', '马其顿'),
        'Macao': ('Macao SAR China', '中国澳门'),
        'Macao SAR China': ('Macao SAR China', '中国澳门'),
        'Madagascar': ('Madagascar', '马达加斯加'),
        'Malawi': ('Malawi', '马拉维'),
        'Malaysia': ('Malaysia', '马来西亚'),
        'Maldives': ('Maldives', '马尔代夫'),
        'Mali': ('Mali', '马里'),
        'Malta': ('Malta', '马耳他'),
        'Marshall Islands': ('Marshall Islands', '马绍尔群岛'),
        'Martinique': ('Martinique', '马提尼克岛'),
        'Mauritania': ('Mauritania', '毛里塔尼亚'),
        'Mauritius': ('Mauritius', '毛里求斯'),
        'Mayotte': ('Mayotte', '马约特岛'),
        'Mexico': ('Mexico', '墨西哥'),
        'Micronesia, Federated States of': ('Micronesia, Federated States of', '密克罗尼西亚联邦'),
        'Moldova': ('Moldova', '摩尔多瓦'),
        'Monaco': ('Monaco', '摩纳哥'),
        'Mongolia': ('Mongolia', '蒙古'),
        'Montserrat': ('Montserrat', '蒙特塞拉特'),
        'Morocco': ('Morocco', '摩洛哥'),
        'Mozambique': ('Mozambique', '莫桑比克'),
        'Namibia': ('Namibia', '纳米比亚'),
        'Nauru': ('Nauru', '瑙鲁'),
        'Navassa Island': ('Navassa Island', '纳瓦萨岛'),
        'Nepal': ('Nepal', '尼泊尔'),
        'Netherlands': ('Netherlands', '荷兰'),
        'Netherlands Antilles': ('Netherlands Antilles', '荷属安的列斯'),
        'New Caledonia': ('New Caledonia', '新喀里多尼亚'),
        'New Zealand': ('New Zealand', '新西兰'),
        'Nicaragua': ('Nicaragua', '尼加拉瓜'),
        'Niger': ('Niger', '尼日尔'),
        'Nigeria': ('Nigeria', '尼日利亚'),
        'Niue': ('Niue', '纽埃'),
        'Norfolk Island': ('Norfolk Island', '诺福克岛'),
        'North Korea': ('North Korea', '朝鲜'),
        'North Macedonia': ('North Macedonia', '北马其顿'),
        'Northern Mariana Islands': ('Northern Mariana Islands', '北马里亚纳群岛'),
        'Norway': ('Norway', '挪威'),
        'Oman': ('Oman', '阿曼'),
        'Pakistan': ('Pakistan', '巴基斯坦'),
        'Palau': ('Palau', '帕劳'),
        'Panama': ('Panama', '巴拿马'),
        'Papua New Guinea': ('Papua New Guinea', '巴布亚新几内亚'),
        'Paracel Islands': ('Paracel Islands', '西沙群岛'),
        'Paraguay': ('Paraguay', '巴拉圭'),
        'Peru': ('Peru', '秘鲁'),
        'Philippines': ('Philippines', '菲律宾'),
        'Pitcairn Islands': ('Pitcairn Islands', '皮特凯恩群岛'),
        'Poland': ('Poland', '波兰'),
        'Portugal': ('Portugal', '葡萄牙'),
        'Puerto Rico': ('Puerto Rico', '波多黎各'),
        'Qatar': ('Qatar', '卡塔尔'),
        'Reunion': ('Reunion', '留尼汪'),
        'Romania': ('Romania', '罗马尼亚'),
        'Russia': ('Russia', '俄罗斯'),
        'Russian Federation': ('Russia', '俄罗斯'),
        'Rwanda': ('Rwanda', '卢旺达'),
        'Saint Barthélemy': ('Saint Barthélemy', '圣巴泰勒米'),
        'Saint Helena': ('Saint Helena', '圣赫勒拿岛'),
        'Saint Kitts and Nevis': ('Saint Kitts and Nevis', '圣基茨和尼维斯'),
        'Saint Lucia': ('Saint Lucia', '圣卢西亚岛'),
        'Saint Pierre and Miquelon': ('Saint Pierre and Miquelon', '圣皮埃尔和密克隆群岛'),
        'Saint Vincent and the Grenadines': ('Saint Vincent and the Grenadines', '圣文森特和格林纳丁斯'),
        'Samoa': ('Samoa', '萨摩亚'),
        'San Marino': ('San Marino', '圣马力诺'),
        'Sao Tome and Principe': ('Sao Tome and Principe', '圣多美和普林西比'),
        'Saudi Arabia': ('Saudi Arabia', '沙特阿拉伯'),
        'Senegal': ('Senegal', '塞内加尔'),
        'Serbia': ('Serbia', '塞尔维亚'),
        'Serbia and Montenegro': ('Serbia and Montenegro', '塞尔维亚和黑山'),
        'Seychelles': ('Seychelles', '塞舌尔群岛'),
        'Sierra Leone': ('Sierra Leone', '塞拉利昂'),
        'Singapore': ('Singapore', '新加坡'),
        'Sint Maarten (Dutch part)': ('Sint Maarten (Dutch part)', '荷属圣马丁'),
        'Slovakia': ('Slovakia', '斯洛伐克'),
        'Slovenia': ('Slovenia', '斯洛文尼亚'),
        'Solomon Islands': ('Solomon Islands', '所罗门群岛'),
        'Somalia': ('Somalia', '索马里'),
        'South Africa': ('South Africa', '南非'),
        'South Georgia and the South Sandwich Islands': ('South Georgia and the South Sandwich Islands', '南乔治亚岛和南桑威奇群岛'),
        'South Korea': ('South Korea', '韩国'),
        'Republic of Korea': ('South Korea', '韩国'),
        'South Sudan': ('South Sudan', '南苏丹'),
        'Spain': ('Spain', '西班牙'),
        'Spratly Islands': ('Spratly Islands', '南沙群岛'),
        'Sri Lanka': ('Sri Lanka', '斯里兰卡'),
        'Sudan': ('Sudan', '苏丹'),
        'Suriname': ('Suriname', '苏里南'),
        'Svalbard': ('Svalbard', '斯瓦尔巴群岛'),
        'Swaziland': ('Swaziland', '斯威士兰'),
        'Sweden': ('Sweden', '瑞典'),
        'Switzerland': ('Switzerland', '瑞士'),
        'Syria': ('Syria', '叙利亚'),
        'Tajikistan': ('Tajikistan', '塔吉克斯坦'),
        'Taiwan': ('Taiwan, Province of China', '中国台湾'),
        'Taiwan, Province of China': ('Taiwan, Province of China', '中国台湾'),
        'Taiwan Province of China': ('Taiwan, Province of China', '中国台湾'),
        'Tanzania': ('Tanzania', '坦桑尼亚'),
        'Thailand': ('Thailand', '泰国'),
        'Timor-Leste': ('Timor-Leste', '东帝汶'),
        'Togo': ('Togo', '多哥'),
        'Tokelau': ('Tokelau', '托克劳'),
        'Tonga': ('Tonga', '汤加'),
        'Trinidad and Tobago': ('Trinidad and Tobago', '特立尼达和多巴哥'),
        'Tromelin Island': ('Tromelin Island', '特罗姆兰岛'),
        'Tunisia': ('Tunisia', '突尼斯'),
        'Turkey': ('Turkey', '土耳其'),
        'Turkmenistan': ('Turkmenistan', '土库曼斯坦'),
        'Turks and Caicos Islands': ('Turks and Caicos Islands', '特克斯和凯科斯群岛'),
        'Tuvalu': ('Tuvalu', '图瓦卢'),
        'Uganda': ('Uganda', '乌干达'),
        'Ukraine': ('Ukraine', '乌克兰'),
        'United Arab Emirates': ('United Arab Emirates', '阿联酋'),
        'United Kingdom': ('United Kingdom', '英国'),
        'United States': ('United States', '美国'),
        'United States of America': ('United States', '美国'),
        'United States Virgin Islands': ('United States Virgin Islands', '美属维尔京群岛'),
        'Uruguay': ('Uruguay', '乌拉圭'),
        'Uzbekistan': ('Uzbekistan', '乌兹别克斯坦'),
        'Vanuatu': ('Vanuatu', '瓦努阿图'),
        'Venezuela': ('Venezuela', '委内瑞拉'),
        'Vietnam': ('Vietnam', '越南'),
        'Virgin Islands': ('Virgin Islands', '维尔京群岛'),
        'Wake Island': ('Wake Island', '威克岛'),
        'Wallis and Futuna': ('Wallis and Futuna', '瓦利斯和富图纳群岛'),
        'Western Sahara': ('Western Sahara', '西撒哈拉'),
        'Yemen': ('Yemen', '也门'),
        'Zambia': ('Zambia', '赞比亚'),
        'Zimbabwe': ('Zimbabwe', '津巴布韦'),
    }
    
    # 将国家名称翻译为指定的语言
    if language == 'zh':
        country_names = [country_translations.get(name, (name, name))[1] for name in country_names]
    else:
        country_names = [country_translations.get(name, (name, name))[0] for name in country_names]

    # 将多个国家的名称用 "·" 连接起来
    country = ' · '.join(country_names)

    return country
